export const ADD_HISTORY = 'ADD_HISTORY';
export const ADVANCE_HISTORY = 'ADVANCE_HISTORY';
export const REVERT_HISTORY = 'REVERT_HISTORY';

export const CHANGE_ORDER = 'CHANGE_ORDER';

export const ADVANCE_STEP_NUMBER = 'ADVANCE_STEP_NUMBER';

export const JUDGE_THE_GAME = 'JUDGE_THE_GAME';
