export const UPDATE_HISTORY = 'UPDATE_HISTORY';
export const RESET_HISTORY = 'RESET_HISTORY'

export const ADD_STEP_NUMBER = 'ADD_STEP_NUMBER';
export const SUBTRACT_STEP_NUMBER = 'SUBTRACT_STEP_NUMBER';
export const RESET_STEP_NUMBER = 'RESET_HISTORY_NUMBER'

export const JUDGE_THE_GAME = 'JUDGE_THE_GAME';
export const RESET_RESULT = 'RESET_RESULT';
